### ISSUE TITLE
Lender tries to replace loan transaction

### ISSUE THREAD

**Issue by da-kami** [comit-network/waves#213] opened 2021-08-03 02:03 UTC
When taking out two loans shortly after each other I ran into this problem on the lender side:

```
2021-08-03T01:59:51.733630Z ERROR bobtimus::problem: unhandled error: JSON-RPC request failed with code -26: insufficient fee, rejecting replacement 4094c7509ac5e9f8514b4fa1fa893c628b3ff9257fc6b53cb78ae419daa3385a, not enough additional fees to relay; 0.00000107 < 0.00000507 (code 66): JSON-RPC request failed with code -26: insufficient fee, rejecting replacement 4094c7509ac5e9f8514b4fa1fa893c628b3ff9257fc6b53cb78ae419daa3385a, not enough additional fees to relay; 0.00000107 < 0.00000507 (code 66)

```

Which results in a `500` on the borrower side, but the loan still shows up in the loan list (!). 

We should:

* Find out why the lending side fails to publish and avoid / fix such scenarios
* Make sure the borrowing side deals with the error and NOT display the loan in the list

**Comment by bonomat** [comment] 2021-08-03 02:32
duplicate of #200

**Closed by bonomat** 2021-08-03 02:32 UTC
